sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aymanaloshan/docker-react -f Dockerfile.dev .

script:
  - docker run aymanaloshan/docker-react npm run test -- --coverage
